# Generated by Django 5.0.1 on 2024-02-06 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.menucategory'),
        ),
    ]
